export const initialProjects = [
  {
    id: "1",
    title: "Raspberry Pi Weather Station",
    slug: "raspberry-pi-weather-station",
    description:
      "This project will guide you on how to create a personal weather station using a Raspberry Pi. The station will be capable of tracking temperature, humidity, and air pressure in real time. You'll learn basic Python scripting and data management.",
    materials: [
      "Raspberry Pi board",
      "Weather sensor",
      "Micro SD card",
      "Power supply",
      "Python",
    ],
    duration: "2 days",
    complexity: "Advanced",
    steps: [
      { id: 1, desc: "Setup Raspberry Pi with Raspbian." },
      { id: 2, desc: "Connect weather sensor to Raspberry Pi." },
      { id: 3, desc: "Write Python script to read data from weather sensor." },
      { id: 4, desc: "Set script to run at regular intervals." },
      { id: 5, desc: "Display data on a dashboard or send it to an email." },
    ],
    image: "/images/weather-station.png",
    favorite: false,
  },
  {
    id: "2",
    title: "Gardening Sensor System",
    slug: "gardening-sensor-system",
    description:
      "You will create a smart gardening system that measures soil moisture and air temperature. The system can control water pumps automatically to maintain optimal conditions for your plants. You'll get hands-on experience with Arduino programming and hardware interfacing.",
    materials: [
      "Arduino board",
      "Soil moisture sensor",
      "Temperature sensor",
      "Water pump",
      "Relay",
    ],
    duration: "3 days",
    complexity: "Advanced",
    steps: [
      {
        id: 1,
        desc: "Connect soil moisture and temperature sensors to Arduino.",
      },
      { id: 2, desc: "Write a program to read data from the sensors." },
      {
        id: 3,
        desc: "Link the water pump to the relay and program it to activate when soil is dry.",
      },
      { id: 4, desc: "Implement temperature control using fans or heaters." },
      { id: 5, desc: "Test the system in your garden." },
    ],
    image: "/images/gardening-sensor-system.png",
    favorite: false,
  },
  {
    id: "3",
    title: "Smart Mirror",
    slug: "smart-mirror",
    description:
      "Create a smart mirror that displays real-time weather updates, news headlines, calendar events, and more. You'll use a Raspberry Pi to power the mirror and run MagicMirror² software. This project will give you experience in JavaScript programming and hardware setup.",
    materials: [
      "Two-way mirror",
      "Monitor",
      "Raspberry Pi board",
      "HDMI cable",
      "JavaScript",
    ],
    duration: "1 week",
    complexity: "Advanced",
    steps: [
      { id: 1, desc: "Install MagicMirror² on your Raspberry Pi." },
      { id: 2, desc: "Configure MagicMirror² to display desired information." },
      { id: 3, desc: "Connect Raspberry Pi to monitor via HDMI cable." },
      { id: 4, desc: "Place two-way mirror over the monitor." },
      { id: 5, desc: "Encase everything in a custom frame." },
    ],
    image: "/images/smart-mirror.png",
    favorite: false,
  },
  {
    id: "4",
    title: "Fancy Birdhouse",
    slug: "diy-birdhouse",
    description:
      "Create a beautiful birdhouse for your feathery friends in your backyard. You'll learn basic woodworking skills including cutting wooden boards and assembling parts with screws. You can customize the design as per your preference and paint it with your favorite colors.",
    materials: ["Wooden boards", "Screws", "Drill", "Saw", "Paint"],
    duration: "1 day",
    complexity: "Beginner",
    steps: [
      {
        id: 1,
        desc: "Design the birdhouse and mark measurements on the wooden boards.",
      },
      { id: 2, desc: "Use a saw to cut the boards according to your design." },
      { id: 3, desc: "Assemble the birdhouse using screws and a drill." },
      { id: 4, desc: "Drill a hole in the front for an entrance." },
      { id: 5, desc: "Paint or stain the birdhouse as desired." },
    ],
    image: "/images/diy-birdhouse.png",
    favorite: false,
  },
];
